### ISSUE TITLE
[UIImage imageNamed:] 释放时机

### ISSUE THREAD

**Issue by dexterhahaha** [DevDragonLi/iOSInterviewsAndDevNotes#1]
如果没有使用局部释放池，并且在主线程，则是当前主线程Runloop一次循环结束前释放。

**Comment by DevDragonLi** [comment]
The description will be confirmed and updated  MD files later

**Comment by qingfengiOS** [comment]
官方说法：
the class holds onto cached objects only while the object exists. If all strong references to the image are subsequently removed, the object may be quietly removed from the cache. Thus, if you plan to hold onto a returned image object, you must maintain a strong reference to it like you would any Cocoa object.
