### ISSUE TITLE
关于最后一个抖音商业化的面试题

### ISSUE THREAD

**Issue by Davisjy** [DevDragonLi/iOSInterviewsAndDevNotes#2]
只有这么一点吗

**Comment by DevDragonLi** [comment]
@Davisjy 经过我多方打探，四处奔波，结论同步如下：

- 此份面试题为微信掘金技术内，某同学面试后**一段时间后**总结汇总给到我的，故而为**不完整版本**，全部题目已为烟云不可考证。
- 面试题核心点应该是不存在遗失的。
